### PR TITLE
crack at #462

### PR DESCRIPTION
**Pull request by Gamnn**
Output NTSC activeVideoEnd as 760 from activeVideoStart, if it doesn't exceed fieldWidth. There's probably a more elegant way to do this.

### CODE REVIEW

**Comment by Gamnn** [comment]
This is a bit hack-y. I _think_ changing line 73 in core.py to
```
    'activeVideoUS': (9.45, 63.555-1.0),
```
and line 93 to
```
SysParams_NTSC['activeVideoUS'] = (9.45, SysParams_NTSC['line_period'] - 1.0)
```
might work, but I've not had time to test.

**Comment by simoninns** [comment]
The timings should be according to the NTSC specifications as-is?  Either way, I'd advise a complete regression test of all tools for NTSC before this is merged as the timings are used by pretty much everything in the processing chain.

**Comment by simoninns** [comment]
In other words @Gamn - did you test this change across all tools in your branch before requesting a merge?

**Comment by Gamnn** [comment]
I've tested the hacky-solution that only modifies the json output, but not the change to activeVideoUS, which I haven't committed yet, pending input from @happycube.

**Comment by Gamnn** [comment]
activeVideoUS adjustment tested and committed. Seems good on what I've tested so far.

**Pull request merged**
